### ISSUE TITLE
Windows problem

### ISSUE THREAD

**Issue by chpio** [akoenig/gulp-svg2png#8]
Hi,

i have a problem with gulp-svg2png:

```
C:\project\node_modules\gulp-svg2png\index.js:59
        throw new gutil.PluginError(PLUGIN_NAME, message);
              ^
Error in plugin '←[36mgulp-svg2png←[39m'
Error while converting image.Error: TypeError: 'undefined' is not a function (evaluating 'el.getBBox()')

  phantomjs://webpage.evaluate():5
  phantomjs://webpage.evaluate():35
  phantomjs://webpage.evaluate():35
Unable to calculate dimensions.
TypeError: 'null' is not an object (evaluating 'dimensions.width')
    at error (C:\project\node_modules\gulp-svg2png\index.js:59:15)
    at converted (C:\project\node_modules\gulp-svg2png\index.js:160:24)
    at C:\project\node_modules\gulp-svg2png\node_modules\svg2png\lib\svg2png.js:20:13
    at ChildProcess.exithandler (child_process.js:646:7)
    at ChildProcess.emit (events.js:98:17)
    at maybeClose (child_process.js:756:16)
    at Process.ChildProcess._handle.onexit (child_process.js:823:5)
```

**Comment by mikriot** [comment]
Hi guys!
I found that the error occurs at the absence of this line in the svg file:
```
<?xml version="1.0" encoding="UTF-8"?>
```
If you use **imagemin-svgo** or **svgmin** then you need add the option `{removeXMLProcInst: false}` in the plugin settings. It will look something like this:

```
svgo: {
    plugins: [
        {removeXMLProcInst: false}, // Prevents removal of the xml header
        {removeViewBox: false}
    ]
}
```
Good luck!

**Comment by mikriot** [comment]
Hi **bloooooooop**. Please see this example:

```
var gulp           = require('gulp'),
    svgo           = require('gulp-svgo'),
    svg2png        = require('gulp-svg2png');

gulp.task('svg2png', function () {
    gulp.src('./src/svg/**/*.svg')
        .pipe(svgo({
            plugins: [
                {removeXMLProcInst: false}
            ]
        }))
        .pipe(svg2png())
        .pipe(gulp.dest('./dest/png/'));
});
```
Note that the source svg files must have the xml header.

**Comment by bloooooooop** [comment]
Hi mikriot,
I have not error but my sprite.svg and sprite.png are not generated. I'm looking at it.

**Comment by akoenig** [comment]
Awesome collaboration @bloooooooop @mikriot!

**Comment by t128** [comment]
@akoenig can you keep this open, so anyone can see this and fix the xml-header error
